In [1]:
%matplotlib notebook
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import os 
os.chdir('/Users/nicol/Documents/python xls files')
import pandas as pd
import numpy as np

data = pd.read_excel('158 supraorb python EDIT.xlsx')
data

label_l  color_l      x1_l      y1_l      z1_l  \
0                hoek oogkast links        1  199.6170 -298.8019  257.8874   
1               hoek oogkast rechts        1  163.4619 -203.6229  264.4583   
2        botkraakbeen overgang neus        1  188.0519 -249.4377  294.6642   
3            sulcus supra orbitalis        3  174.7794 -282.6521  279.6166   
4        n supraorbitalis splitsing        5  173.4252 -283.6554  267.7842   
5       MEDIAAL mid splitsing - mid        5  170.3617 -284.7623  288.0873   
6                               mid        5  160.4310 -287.0850  287.7110   
7                    mid dist - mid        5  145.4510 -288.3270  292.9060   
8                  mediale tak dist        5  124.6240 -287.2720  291.9130   
9        n supraorbitalis splitsing        6  173.4252 -283.6554  267.7842   
10        INTER mid splitsing - mid        6       NaN       NaN       NaN   
11                              mid        6       NaN       NaN       NaN   
12                   mid dist - mid        6       NaN       NaN       NaN   
13                   inter tak dist        6       NaN       NaN       NaN   
14       n supraorbitalis splitsing        7  173.4252 -283.6554  267.7842   
15     LATERAAL mid splitsing - mid        7   78.0222 -246.6524  309.2320   
16                              mid        7   58.6784 -255.0087  306.4415   
17                   mid dist - mid        7   42.7418 -258.2407  301.0526   
18                laterale tak dist        7   25.5792 -260.8072  291.1673   
19                        lat onder        8  196.0606 -301.2145  258.0521   
20                        mid onder        8  177.7245 -290.4295  281.8201   
21                        med onder        8  175.2189 -265.4988  286.3208   
22  corrugator supercilii med boven        8  161.8070 -268.8814  290.7408   
23                        mid boven        8  167.7999 -292.5403  283.7156   
24                        lat boven        8  186.9117 -306.0477  256.9115   
25               doorboring med tak        9  170.3617 -284.7623  288.0873   
26          doorboring intermed tak        9       NaN       NaN       NaN   
27               doorboring lat tak        9       NaN       NaN       NaN   
28              frontalis basis med       10  165.0498 -272.8965  291.2731   
29                          med mid       10  139.6172 -276.1518  287.2049   
30                         med dist       10  115.3692 -280.6863  280.0311   
31                   mid prox - med       10  116.8325 -296.7844  273.4139   
32                         prox mid       10  121.3880 -311.6305  263.3513   
33                   mid prox - lat       10  133.0312 -321.4489  252.9215   
34                         lat dist       10  139.9165 -327.6480  248.0012   
35                          lat mid       10  159.1044 -317.8612  260.2620   
36                        basis lat       10  179.1983 -305.8980  266.8196   

                            label_r  color_r      x1_r      y1_r      z1_r  
0                hoek oogkast links        1  200.8502 -299.0164  257.7351  
1               hoek oogkast rechts        1  164.2973 -203.9066  264.2433  
2        botkraakbeen overgang neus        1  189.2762 -249.4438  294.5932  
3            sulcus supra orbitalis        3  164.5668 -232.8081  285.8972  
4        n supraorbitalis splitsing        5  163.8367 -232.1667  285.5962  
5       MEDIAAL mid splitsing - mid        5   75.7274 -176.2288  313.2676  
6                               mid        5   61.3712 -173.6093  312.0295  
7                    mid dist - mid        5   47.0552 -173.1594  308.9387  
8                  mediale tak dist        5   31.4008 -175.6313  304.3633  
9        n supraorbitalis splitsing        6  163.8367 -232.1667  285.5962  
10        INTER mid splitsing - mid        6   70.2513 -169.8973  306.1786  
11                              mid        6   50.4927 -166.4500  303.3439  
12                   mid dist - mid        6   29.8487 -165.50

In [24]:
Begin = np.array(data.iloc[25, np.array([7,8,9])]).reshape(1,3)
P1    = np.array(data.iloc[10, np.array([7,8,9])]).reshape(1,3)
P2    = np.array(data.iloc[11, np.array([7,8,9])]).reshape(1,3)
P3    = np.array(data.iloc[12, np.array([7,8,9])]).reshape(1,3)
P4    = np.array(data.iloc[13, np.array([7,8,9])]).reshape(1,3)

In [25]:
Verschil= P1-Begin
Verschil

array([[-77.98029999999999, 64.91220000000001, 17.70240000000001]],
      dtype=object)

In [26]:
P2-Verschil

array([[128.47299999999998, -231.3622, 285.6415]], dtype=object)

In [27]:
P3-Verschil

array([[107.82899999999998, -230.41670000000002, 277.0626]], dtype=object)

In [28]:
P4-Verschil

array([[91.57559999999998, -233.20770000000002, 271.4581]], dtype=object)